# Generated by Django 5.0.6 on 2024-06-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='facility_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
